/**
 * Action Types - Central definition of all action types
 * Separated from AppContext.jsx to fix Fast Refresh issues
 */

export const ActionTypes = {
  // Cart actions
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  SET_CART: 'SET_CART',
  CLEAR_CART: 'CLEAR_CART',

  // Customer actions
  SET_MOBILE_COST: 'SET_MOBILE_COST',
  SET_NUMBER_OF_LINES: 'SET_NUMBER_OF_LINES',
  SET_ORIGINAL_ITEM_PRICE: 'SET_ORIGINAL_ITEM_PRICE',
  SET_EXISTING_BRANDS: 'SET_EXISTING_BRANDS',
  SET_BROADBAND_COST: 'SET_BROADBAND_COST',
  SET_BUYBACK_AMOUNT: 'SET_BUYBACK_AMOUNT',

  // Streaming actions
  TOGGLE_STREAMING: 'TOGGLE_STREAMING',
  SET_STREAMING: 'SET_STREAMING',
  CLEAR_STREAMING: 'CLEAR_STREAMING',

  // Settings actions
  SET_THEME: 'SET_THEME',
  SET_CASH_DISCOUNT: 'SET_CASH_DISCOUNT',
  SET_CASH_DISCOUNT_LOCKED: 'SET_CASH_DISCOUNT_LOCKED',
  SET_AUTO_ADJUST: 'SET_AUTO_ADJUST',
  SET_SHOW_CASH_DISCOUNT: 'SET_SHOW_CASH_DISCOUNT',
  TOGGLE_CASH_DISCOUNT: 'TOGGLE_CASH_DISCOUNT',
  SET_FREE_SETUP: 'SET_FREE_SETUP',

  // UI actions
  SET_ACTIVE_PROVIDER: 'SET_ACTIVE_PROVIDER',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_DEBOUNCED_SEARCH_QUERY: 'SET_DEBOUNCED_SEARCH_QUERY',
  SET_SHOW_PRESENTATION: 'SET_SHOW_PRESENTATION',
  TOGGLE_PRESENTATION: 'TOGGLE_PRESENTATION',
  SET_SHOW_HELP_GUIDE: 'SET_SHOW_HELP_GUIDE',
  TOGGLE_HELP_GUIDE: 'TOGGLE_HELP_GUIDE',
  SET_CBB_MIX_ENABLED: 'SET_CBB_MIX_ENABLED',
  SET_CBB_MIX_COUNT: 'SET_CBB_MIX_COUNT',
  SET_EAN_SEARCH_RESULTS: 'SET_EAN_SEARCH_RESULTS',
  SET_IS_SEARCHING: 'SET_IS_SEARCHING',

  // System actions
  RESET_ALL: 'RESET_ALL',
  LOAD_STATE: 'LOAD_STATE'
};
